network:
  topology: "typical_complex"
  hyperperiod: 6000
  bandwidth: 1e9
  flows:
    routing_mode: "path" 
    tsn:
      input: 35
      background: 35
      params:
        periods: [100, 500, 1000, 1500, 2000]
        datasizes: [30, 40, 50, 60, 70, 80, 90, 100]
    avb:
      input: 15
      background: 15
      params:
        period: 125
        deadline: 2000
        datasizes: [1000, 1100, 1200, 1300, 1400, 1500]
    can:
      nodes: 5         
      important: 5
      unimportant: 25
      params:
        important_params:
          period: 5000
          deadline: 5000
          datasize: 16
        unimportant_params:
          periods: [50000, 100000, 150000]
          deadlines: [10000, 12000, 14000, 16000, 18000, 20000]
          datasize: 16

algorithm:
  name: "osro"
  osaco:
    timeout: 200
    k_trees: 5
    pheromone_evaporation: 0.7
    method_number: 0

schedule:
  costs:
    o1: 100000000
    o2: 100000
    o3: 0
    o4: 1

experiment:
  test_cases: 100
  random_seed: 1

output:
  show_network: false
  show_plan: false
  log_level: "info"
